
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db-legado-inventario
  title: DB Inventário de Peças (Oracle)
  description: Banco de dados legado com catálogo e estoque de peças.
  tags: [database, oracle, legacy]
spec:
  type: database
  owner: group:squad-maintenance-core
  system: maintenance-manager

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cluster-logs-manutencao
  title: Cluster de Logs (MongoDB)
  tags: [database, mongodb, nosql]
spec:
  type: database
  owner: group:squad-maintenance-core
  system: maintenance-manager

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-eventos-core
  title: Broker Kafka (Core)
  tags: [messaging, kafka, broker]
spec:
  type: message-broker
  owner: group:squad-maintenance-core
  system: maintenance-manager
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db-financeiro-oracle
  title: DB Financeiro Core (Oracle)
  description: Banco de dados relacional transacional de alta performance para o ledger financeiro e controle de assinaturas.
  tags: [database, oracle, pl-sql, finance]
spec:
  type: database
  owner: group:squad-billing
  system: billing-gateway
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bucket-notas-fiscais
  title: Storage de Notas Fiscais (S3)
  description: Armazenamento de arquivos XML e PDF das notas fiscais emitidas.
  tags: [storage, aws-s3]
spec:
  type: s3-bucket
  owner: group:squad-billing
  system: billing-gateway

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db-data-warehouse
  title: Data Warehouse (Redshift/PostgreSQL)
  description: Armazém de dados central com dados consolidados da empresa.
  tags: [database, data-warehouse, postgresql]
  annotations:
    github.com/project-slug: myorg/data-analytics-platform
spec:
  type: database
  owner: group:squad-data-analytics
  system: data-analytics
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bucket-datalake
  title: Data Lake S3 (Raw Data)
  description: Bucket de armazenamento de objetos para dados brutos não estruturados.
  tags: [storage, aws-s3, datalake]
  annotations:
    github.com/project-slug: myorg/data-analytics-platform
spec:
  type: s3-bucket
  owner: group:squad-data-analytics
  system: data-analytics
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-cluster-analytics
  title: Broker Kafka (Analytics)
  description: Cluster Kafka dedicado para processamento de streaming de dados.
  tags: [messaging, kafka, data-streaming]
  annotations:
    github.com/project-slug: myorg/data-analytics-platform
spec:
  type: message-broker
  owner: group:squad-data-analytics
  system: data-analytics

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db-usuarios-iam
  title: DB Usuários e Permissões (PostgreSQL)
  description: Banco de dados relacional com as credenciais criptografadas e roles.
  tags: [database, postgresql, security]
  annotations:
    github.com/project-slug: myorg/identity-access-platform
spec:
  type: database
  owner: group:squad-identity
  system: identity-access
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cache-sessoes-redis
  title: Cache de Sessões (Redis)
  description: Cluster Redis para armazenamento de sessões ativas e tokens revogados (blocklist).
  tags: [cache, redis, in-memory]
  annotations:
    github.com/project-slug: myorg/identity-access-platform
spec:
  type: database
  owner: group:squad-identity
  system: identity-access
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-auditoria-iam
  title: Broker Kafka (Segurança)
  description: Broker dedicado para eventos de segurança e auditoria (isolado por compliance).
  tags: [messaging, kafka, security]
  annotations:
    github.com/project-slug: myorg/identity-access-platform
spec:
  type: message-broker
  owner: group:squad-identity
  system: identity-access
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cache-bff-redis
  title: Cache de Respostas (Redis)
  description: Cache em memória para aliviar requisições repetitivas dos BFFs para os microsserviços core.
  tags: [cache, redis]
  annotations:
    github.com/project-slug: myorg/customer-portal-platform
spec:
  type: database
  owner: group:squad-frontend
  system: customer-portal


---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k8s-cluster-platform
  title: Cluster Kubernetes (Platform Core)
  description: Cluster EKS dedicado para rodar as ferramentas internas da engenharia.
  tags: [infrastructure, kubernetes, aws]
  annotations:
    github.com/project-slug: myorg/devex-platform
spec:
  type: cluster
  owner: group:squad-devex
  system: devex-platform
